class Config:

	repo_file = '/JavaRepositories/Repos.xlsx'
	final = '/JavaRepositories/FINAL.xlsx'
	final2 = '/JavaRepositories/LogMetrics-Summarized.xlsx'
	excel2repo = '/JavaRepositories/scripts/files/log_instances/input/excel2repo.json'
	log_count = '/JavaRepositories/scripts/files/log_instances/log_count.json'
	logvsnonlog = '/JavaRepositories/scripts/files/logvnlog/logvsnlog_changes.json'
	pattern_op = '/JavaRepositories/scripts/files/log_level/pattern_output.json'
	finalexport = '/JavaRepositories/scripts/finalexport.py'
	finalexport2 = '/JavaRepositories/scripts/finalexport2.py'
	gini_index = '/JavaRepositories/gini_index.xlsx'
	semgrep_logcount = 'https://semgrep.dev/s/krishnatejaj:log_count_java'
	semgrep_loglevel = 'https://semgrep.dev/s/krishnatejaj:log_level_java'

	research = '/JavaRepositories/'
	scripts = '/JavaRepositories/scripts/'
	files = '/JavaRepositories/scripts/files/'
	datascience = '/JavaRepositories/DataScience/'
	nondatascience = '/JavaRepositories/NonDataScience/'
	log_instances = '/JavaRepositories/scripts/files/log_instances/'
	log_instances_input = '/JavaRepositories/scripts/files/log_instances/input/'
	log_level = '/JavaRepositories/scripts/files/log_level/'
	logvnlog = '/JavaRepositories/scripts/files/logvnlog/'
